const path = require("path");
require("dotenv").config({ path: path.join(__dirname, ".env") });
const mongoose = require("mongoose");
const User = require("./src/features/user/User");
const JobPost = require("./src/features/jobPost/jobPost");
const Message = require("./src/features/messaging/message");
const Application = require("./src/features/application/Application");

async function seed() {
  const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI;

  if (!mongoUri) {
    throw new Error("MongoDB connection string is missing. Set MONGO_URI or MONGODB_URI.");
  }

  await mongoose.connect(mongoUri);

  await User.deleteMany({});
  await JobPost.deleteMany({});
  await Message.deleteMany({});
  await Application.deleteMany({});

  const [admin, seeker, recruiter] = await User.create([
    {
      name: "Admin",
      email: "admin@giunexus.com",
      password: "adminpassword123",
      role: "admin",
      status: "approved",
    },
    {
      name: "Job Seeker",
      email: "seeker@test.com",
      password: "seeker123",
      role: "jobSeeker",
      status: "approved",
    },
    {
      name: "Recruiter",
      email: "recruiter@test.com",
      password: "recruiter123",
      role: "recruiter",
      status: "approved",
    },
  ]);

  await User.updateOne({ email: "admin@giunexus.com" }, { $set: { mfaEnabled: false } });

  console.log("Seeded users:");
  console.log("  Admin       — admin@giunexus.com / adminpassword123");
  console.log("  Job Seeker  — seeker@test.com / seeker123");
  console.log("  Recruiter   — recruiter@test.com / recruiter123");

  const recruiterId = recruiter._id;

  const createdJobs = await JobPost.create([
    {
      title: "Senior Frontend Engineer",
      company: "NovaTech",
      description: "Lead the development of our next-generation web platform using React and TypeScript. You will architect scalable UI systems and mentor junior developers.",
      requirements: ["React", "TypeScript", "CSS Architecture", "Performance Optimization", "Git"],
      location: { city: "Berlin", country: "Germany" },
      type: "full-time",
      salary: { min: 85000, max: 120000, currency: "EUR", period: "yearly", isPublic: true },
      category: "Engineering",
      totalSlots: 3,
      status: "open",
      createdBy: recruiterId,
      viewCount: 2841,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Unlimited PTO", "Learning Budget", "Home Office Stipend"],
      experience: { minYears: 5 },
      requiredEducation: "bachelor",
      requiredEducationField: "Computer Science",
    },
    {
      title: "ML Platform Engineer",
      company: "DeepVault AI",
      description: "Design and build the infrastructure powering our ML training pipelines. Work with GPU clusters, data pipelines, and model serving systems.",
      requirements: ["Python", "Kubernetes", "Docker", "MLOps", "TensorFlow"],
      location: { city: "San Francisco", country: "USA" },
      type: "full-time",
      salary: { min: 160000, max: 220000, currency: "USD", period: "yearly", isPublic: true },
      category: "AI / Machine Learning",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 3120,
      workplaceType: "hybrid",
      perks: ["Equity", "Relocation", "Conference Budget"],
      experience: { minYears: 3 },
      requiredEducation: "master",
      requiredEducationField: "Computer Science",
    },
    {
      title: "Full Stack Developer",
      company: "Helios Labs",
      description: "Build end-to-end features across our SaaS platform from database to UI. We use Node.js, React, and PostgreSQL.",
      requirements: ["Node.js", "React", "PostgreSQL", "REST APIs", "JavaScript"],
      location: { city: "Toronto", country: "Canada" },
      type: "full-time",
      salary: { min: 95000, max: 130000, currency: "USD", period: "yearly", isPublic: true },
      category: "Engineering",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 1950,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Health & Dental", "Stock Options", "Annual Retreat"],
      experience: { minYears: 3 },
      requiredEducation: "bachelor",
    },
    {
      title: "DevOps Engineer",
      company: "CloudForge",
      description: "Automate and scale our cloud infrastructure across AWS. Manage CI/CD pipelines, monitoring, and incident response.",
      requirements: ["AWS", "Terraform", "Docker", "CI/CD", "Linux Administration"],
      location: { city: "Austin", country: "USA" },
      type: "full-time",
      salary: { min: 130000, max: 175000, currency: "USD", period: "yearly", isPublic: true },
      category: "DevOps / Infrastructure",
      totalSlots: 1,
      status: "open",
      createdBy: recruiterId,
      viewCount: 1340,
      workplaceType: "hybrid",
      perks: ["401k Match", "Parental Leave", "Wellness Stipend"],
      experience: { minYears: 4 },
      requiredEducation: "bachelor",
    },
    {
      title: "Product Designer",
      company: "PixelCraft Studio",
      description: "Own the end-to-end design of our mobile and web products. From research and wireframes to pixel-perfect handoff.",
      requirements: ["Figma", "User Research", "Prototyping", "Design Systems", "Accessibility"],
      location: { city: "London", country: "UK" },
      type: "full-time",
      salary: { min: 65000, max: 85000, currency: "GBP", period: "yearly", isPublic: true },
      category: "Design",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 980,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Creative Days", "Design Conference Budget", "Equipment Allowance"],
      experience: { minYears: 3 },
      requiredEducation: "bachelor",
      requiredEducationField: "Design",
    },
    {
      title: "Data Analyst Intern",
      company: "QuantumLeap",
      description: "Join our analytics team for a 12-week internship. You will work on real business problems, build dashboards, and present insights to stakeholders.",
      requirements: ["SQL", "Python", "Tableau", "Statistics", "Communication"],
      location: { city: "New York", country: "USA" },
      type: "internship",
      salary: { min: 35, max: 45, currency: "USD", period: "hourly", isPublic: true },
      category: "Data & Analytics",
      totalSlots: 5,
      status: "open",
      createdBy: recruiterId,
      viewCount: 2680,
      workplaceType: "on_site",
      experience: { minYears: 0 },
      requiredEducation: "bachelor",
    },
    {
      title: "Cybersecurity Analyst",
      company: "SentinelGuard",
      description: "Monitor, detect, and respond to security threats across our enterprise environment. Conduct vulnerability assessments and promote security best practices.",
      requirements: ["Network Security", "SIEM Tools", "Penetration Testing", "Incident Response", "Risk Assessment"],
      location: { city: "Washington DC", country: "USA" },
      type: "full-time",
      salary: { min: 110000, max: 150000, currency: "USD", period: "yearly", isPublic: true },
      category: "Security",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 760,
      workplaceType: "on_site",
      perks: ["Clearance Bonus", "Training Budget", "Flexible Hours"],
      experience: { minYears: 3 },
      requiredEducation: "bachelor",
      requiredEducationField: "Information Security",
    },
    {
      title: "Backend Engineer (Go)",
      company: "StreamlineIO",
      description: "Build high-throughput microservices in Go powering real-time data streams at scale. Focus on reliability, latency, and clean architecture.",
      requirements: ["Go", "Microservices", "gRPC", "Redis", "PostgreSQL"],
      location: { city: "Amsterdam", country: "Netherlands" },
      type: "full-time",
      salary: { min: 75000, max: 105000, currency: "EUR", period: "yearly", isPublic: true },
      category: "Engineering",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 1620,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Bike Allowance", "Pension Plan", "Relocation Support"],
      experience: { minYears: 2 },
      requiredEducation: "bachelor",
    },
    {
      title: "Technical Writer",
      company: "DocsHQ",
      description: "Create clear, developer-friendly documentation for our API platform. Write guides, tutorials, and reference docs that developers love.",
      requirements: ["Technical Writing", "Markdown", "API Documentation", "Git", "Developer Experience"],
      location: { city: "Remote", country: "Worldwide" },
      type: "full-time",
      salary: { min: 70000, max: 100000, currency: "USD", period: "yearly", isPublic: true },
      category: "Writing",
      totalSlots: 1,
      status: "open",
      createdBy: recruiterId,
      viewCount: 430,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Async Culture", "Write the Docs Conf", "Book Budget"],
      experience: { minYears: 2 },
      requiredEducation: "bachelor",
    },
    {
      title: "iOS Developer",
      company: "AppVista",
      description: "Craft delightful iOS experiences using Swift and SwiftUI. You will own features end-to-end from concept to App Store release.",
      requirements: ["Swift", "SwiftUI", "UIKit", "Xcode", "CI/CD for Mobile"],
      location: { city: "Cupertino", country: "USA" },
      type: "full-time",
      salary: { min: 140000, max: 190000, currency: "USD", period: "yearly", isPublic: true },
      category: "Mobile",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 1105,
      workplaceType: "hybrid",
      perks: ["Apple Equipment", "Fitness Reimbursement", "Sabbatical"],
      experience: { minYears: 4 },
      requiredEducation: "bachelor",
    },
    {
      title: "Marketing Associate",
      company: "BrightPath Media",
      description: "Support our growth marketing team with campaign execution, content creation, and analytics reporting across social and email channels.",
      requirements: ["Social Media Marketing", "Google Analytics", "Copywriting", "Email Marketing", "SEO"],
      location: { city: "Chicago", country: "USA" },
      type: "full-time",
      salary: { min: 55000, max: 72000, currency: "USD", period: "yearly", isPublic: true },
      category: "Marketing",
      totalSlots: 1,
      status: "open",
      createdBy: recruiterId,
      viewCount: 520,
      workplaceType: "on_site",
      experience: { minYears: 1 },
      requiredEducation: "bachelor",
      requiredEducationField: "Marketing",
    },
    {
      title: "QA Automation Engineer",
      company: "TestVault",
      description: "Design and maintain automated test suites for our fintech platform. Work closely with developers to ensure quality at every release.",
      requirements: ["Selenium", "Cypress", "Jest", "CI/CD Integration", "API Testing"],
      location: { city: "Bangalore", country: "India" },
      type: "full-time",
      salary: { min: 1500000, max: 2200000, currency: "USD", period: "yearly", isPublic: true },
      category: "Quality Assurance",
      totalSlots: 3,
      status: "open",
      createdBy: recruiterId,
      viewCount: 870,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Health Insurance", "Internet Reimbursement", "Annual Bonus"],
      experience: { minYears: 2 },
      requiredEducation: "bachelor",
    },
    {
      title: "Part-Time UX Researcher",
      company: "InsightLab",
      description: "Conduct user interviews, usability tests, and synthesize findings to inform product decisions. 20 hours per week.",
      requirements: ["User Interviews", "Usability Testing", "Affinity Mapping", "Survey Design", "Presentation Skills"],
      location: { city: "Remote", country: "USA" },
      type: "part-time",
      salary: { min: 50, max: 70, currency: "USD", period: "hourly", isPublic: true },
      category: "Design",
      totalSlots: 1,
      status: "open",
      createdBy: recruiterId,
      viewCount: 340,
      isRemote: true,
      workplaceType: "remote",
      experience: { minYears: 2 },
      requiredEducation: "master",
      requiredEducationField: "HCI",
    },
    {
      title: "Blockchain Developer",
      company: "ChainVerse",
      description: "Build smart contracts and decentralized protocols on Ethereum and Solana. Contribute to open-source tooling and shape the future of Web3.",
      requirements: ["Solidity", "Rust", "Web3.js", "Ethereum", "Smart Contract Security"],
      location: { city: "Dubai", country: "UAE" },
      type: "full-time",
      salary: { min: 140000, max: 200000, currency: "USD", period: "yearly", isPublic: true },
      category: "Blockchain",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 2050,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Token Allocation", "Remote-First", "Hardware Budget"],
      experience: { minYears: 3 },
      requiredEducation: "bachelor",
    },
    {
      title: "Cloud Architect",
      company: "SkyBridge Systems",
      description: "Define and govern cloud architecture across multi-cloud environments. Lead migration strategies and establish platform engineering standards.",
      requirements: ["AWS", "Azure", "Kubernetes", "Terraform", "Enterprise Architecture"],
      location: { city: "Seattle", country: "USA" },
      type: "full-time",
      salary: { min: 170000, max: 230000, currency: "USD", period: "yearly", isPublic: true },
      category: "DevOps / Infrastructure",
      totalSlots: 1,
      status: "open",
      createdBy: recruiterId,
      viewCount: 920,
      workplaceType: "hybrid",
      perks: ["Equity", "Leadership Development", "Conference Budget"],
      experience: { minYears: 8 },
      requiredEducation: "bachelor",
    },
    {
      title: "Software Engineering Intern",
      company: "NovaTech",
      description: "Spend your summer shipping real features on our core product. Paired 1:1 with a senior engineer, you will learn modern development practices from day one.",
      requirements: ["JavaScript", "Git", "Data Structures", "Problem Solving", "Eagerness to Learn"],
      location: { city: "Berlin", country: "Germany" },
      type: "internship",
      salary: { min: 2000, max: 2800, currency: "EUR", period: "monthly", isPublic: true },
      category: "Engineering",
      totalSlots: 6,
      status: "open",
      createdBy: recruiterId,
      viewCount: 3470,
      workplaceType: "hybrid",
      experience: { minYears: 0 },
      requiredEducation: "bachelor",
    },
    {
      title: "Data Engineer",
      company: "DataPulse",
      description: "Design and maintain data pipelines processing billions of events daily. Build the data warehouse powering all analytics and ML at DataPulse.",
      requirements: ["Apache Spark", "Airflow", "Python", "SQL", "Data Modeling"],
      location: { city: "Singapore", country: "Singapore" },
      type: "full-time",
      salary: { min: 100000, max: 140000, currency: "USD", period: "yearly", isPublic: true },
      category: "Data & Analytics",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 1230,
      workplaceType: "hybrid",
      perks: ["Relocation Package", "Health & Wellness", "Stock Options"],
      experience: { minYears: 4 },
      requiredEducation: "bachelor",
      requiredEducationField: "Computer Science",
    },
    {
      title: "React Native Developer",
      company: "AppVista",
      description: "Build cross-platform mobile apps with React Native. Collaborate with designers and backend engineers to ship polished mobile experiences.",
      requirements: ["React Native", "TypeScript", "Redux", "Mobile CI/CD", "App Store Deployment"],
      location: { city: "Lisbon", country: "Portugal" },
      type: "full-time",
      salary: { min: 55000, max: 80000, currency: "EUR", period: "yearly", isPublic: true },
      category: "Mobile",
      totalSlots: 2,
      status: "open",
      createdBy: recruiterId,
      viewCount: 890,
      isRemote: true,
      workplaceType: "remote",
      perks: ["Surf Lessons", "Relocation Help", "Unlimited Coffee"],
      experience: { minYears: 2 },
      requiredEducation: "bachelor",
    },
    {
      title: "Product Manager",
      company: "Helios Labs",
      description: "Own the roadmap for our developer tools platform. Talk to users, prioritize features, and ship products that developers love.",
      requirements: ["Product Strategy", "User Research", "Data-Driven Decisions", "Agile", "Stakeholder Management"],
      location: { city: "Toronto", country: "Canada" },
      type: "full-time",
      salary: { min: 120000, max: 160000, currency: "USD", period: "yearly", isPublic: true },
      category: "Product",
      totalSlots: 1,
      status: "open",
      createdBy: recruiterId,
      viewCount: 1540,
      workplaceType: "hybrid",
      perks: ["Equity", "Learning Budget", "Flexible Hours"],
      experience: { minYears: 5 },
      requiredEducation: "bachelor",
    },
    {
      title: "AI Research Intern",
      company: "DeepVault AI",
      description: "Collaborate with our research team on cutting-edge NLP and computer vision projects. Publish papers and contribute to open-source releases.",
      requirements: ["PyTorch", "Transformer Architectures", "Python", "Research Methodology", "Academic Writing"],
      location: { city: "San Francisco", country: "USA" },
      type: "internship",
      salary: { min: 40, max: 55, currency: "USD", period: "hourly", isPublic: true },
      category: "AI / Machine Learning",
      totalSlots: 3,
      status: "open",
      createdBy: recruiterId,
      viewCount: 2560,
      workplaceType: "on_site",
      perks: ["GPU Access", "Publication Support", "Mentorship"],
      experience: { minYears: 0 },
      requiredEducation: "master",
      requiredEducationField: "Computer Science",
    },
  ]);

  const now = new Date();

  await Application.create({
    user: seeker._id,
    job: createdJobs[0]._id,
    status: "pending",
    appliedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3)
  });
  
  await Message.create([
    {
      job: createdJobs[0]._id,
      sender: seeker._id,
      recipient: recruiter._id,
      body: "Hi, I'm very interested in the Senior Frontend Engineer role!",
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2)
    },
    {
      job: createdJobs[0]._id,
      sender: recruiter._id,
      recipient: seeker._id,
      body: "Hello! Thanks for reaching out. Your background looks great. When are you free for a call?",
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 1)
    },
    {
      job: createdJobs[0]._id,
      sender: seeker._id,
      recipient: recruiter._id,
      body: "I am available tomorrow anytime between 2pm and 5pm EST.",
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 5)
    }
  ]);

  console.log("\nSeeded 20 fake jobs across multiple categories");
  console.log("Seeded messages for testing conversations");
  console.log('Run "node seed.js" to re-seed at any time.\n');

  process.exit();
}

seed();
